add_newline=true

[character] 
success_symbol = "[➜](bold green)" 

[time]
disabled = false
format = '🕙 $time ($style) '
time_format = "%T"
utc_time_offset = "-5"
style = "grey dimmed"

[username]
style_user = "red #dca9fa"
style_root = "black bold"
format = "👑 [$user]($style) "
disabled = false
show_always = true

[python]
symbol = "🐍 "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[memory_usage]
disabled = false
threshold = -1
symbol = "🐏 "
style = "bold dimmed"
format = "$symbol(${ram_pct})($style) mem "